In [15]:
import tensorflow as tf
import pandas as pd
import numpy as np

In [16]:
hrt = pd.read_csv('heart.csv')
hrt.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   1       145   233    1        2      150      0      2.3      3   
1   67    1   4       160   286    0        2      108      1      1.5      2   
2   67    1   4       120   229    0        2      129      1      2.6      2   
3   37    1   3       130   250    0        0      187      0      3.5      3   
4   41    0   2       130   204    0        2      172      0      1.4      1   

   ca        thal  target  
0   0       fixed       0  
1   3      normal       1  
2   2  reversible       0  
3   0      normal       0  
4   0      normal       0

In [17]:
x1 = hrt.drop(['thal','target'],axis=1)
x1.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   1       145   233    1        2      150      0      2.3      3   
1   67    1   4       160   286    0        2      108      1      1.5      2   
2   67    1   4       120   229    0        2      129      1      2.6      2   
3   37    1   3       130   250    0        0      187      0      3.5      3   
4   41    0   2       130   204    0        2      172      0      1.4      1   

   ca  
0   0  
1   3  
2   2  
3   0  
4   0

In [26]:
x = hrt.drop(['thal','target'],axis=1)
x.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   1       145   233    1        2      150      0      2.3      3   
1   67    1   4       160   286    0        2      108      1      1.5      2   
2   67    1   4       120   229    0        2      129      1      2.6      2   
3   37    1   3       130   250    0        0      187      0      3.5      3   
4   41    0   2       130   204    0        2      172      0      1.4      1   

   ca  
0   0  
1   3  
2   2  
3   0  
4   0

In [18]:
y = hrt['target']
y.head()

0    0
1    1
2    0
3    0
4    0
Name: target, dtype: int64

In [19]:
from sklearn.preprocessing import StandardScaler

In [27]:
std_scale = StandardScaler()
std_scale.fit(x1)
x_norm = std_scale.transform(x)
x_norm

array([[ 0.9338399 ,  0.69141072, -2.05403599, ...,  1.06804543,
         2.28495852, -0.72970605],
       [ 1.3782113 ,  0.69141072,  0.86790253, ...,  0.38022871,
         0.66354767,  2.47465531],
       [ 1.3782113 ,  0.69141072,  0.86790253, ...,  1.3259767 ,
         0.66354767,  1.40653485],
       ...,
       [ 1.1560256 ,  0.69141072,  0.86790253, ...,  1.49793088,
         0.66354767,  0.3384144 ],
       [-0.73255285,  0.69141072,  0.86790253, ..., -0.90942763,
        -0.95786317,  1.40653485],
       [ 0.9338399 , -1.44631834,  0.86790253, ...,  2.52965595,
         0.66354767,  2.47465531]])

In [29]:
x_norm_col = pd.DataFrame(x_norm, index=x.index, columns=x.columns) 
x.update(x_norm_col)
x.head()

age       sex        cp  trestbps      chol       fbs   restecg  \
0  0.933840  0.691411 -2.054036  0.745781 -0.260087  2.394438  1.023554   
1  1.378211  0.691411  0.867903  1.592329  0.757388 -0.417635  1.023554   
2  1.378211  0.691411  0.867903 -0.665131 -0.336877 -0.417635  1.023554   
3 -1.954574  0.691411 -0.106077 -0.100766  0.066273 -0.417635 -1.003485   
4 -1.510203 -1.446318 -1.080056 -0.100766 -0.816818 -0.417635  1.023554   

    thalach     exang   oldpeak     slope        ca  
0  0.034808 -0.696631  1.068045  2.284959 -0.729706  
1 -1.780616  1.435481  0.380229  0.663548  2.474655  
2 -0.872904  1.435481  1.325977  0.663548  1.406535  
3  1.634109 -0.696631  2.099771  2.284959 -0.729706  
4  0.985744 -0.696631  0.294252 -0.957863 -0.729706

In [30]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.4)

In [43]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)
print(x_train.shape[1])
print(x_train.iloc[0])

(181, 12)
(122, 12)
(181,)
(122,)
12
age        -0.732553
sex         0.691411
cp          0.867903
trestbps   -0.439385
chol        0.527016
fbs        -0.417635
restecg     1.023554
thalach     0.726398
exang      -0.696631
oldpeak    -0.479542
slope       0.663548
ca         -0.729706
Name: 128, dtype: float64


In [35]:
from tensorflow.keras import models, layers

model = models.Sequential()

In [36]:
model

In [44]:
def build_model():
    model = models.Sequential()
    model.add(layers.Dense(20, activation = 'relu' , input_shape=(x_train.shape[1],)))
    model.add(layers.Dense(20, activation = 'relu'))
    model.add(layers.Dense(1, activation = 'sigmoid'))
    model.compile(optimizer='rmsprop', loss='binary_crossentropy', metrics=['accuracy'])
    return model

In [45]:
model = build_model()

In [46]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 20)                260       
_________________________________________________________________
dense_1 (Dense)              (None, 20)                420       
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 21        
Total params: 701
Trainable params: 701
Non-trainable params: 0
_________________________________________________________________


In [48]:
hist = model.fit(x_train, y_train, epochs=10, batch_size=1, verbose=1)

Train on 181 samples
Epoch 1/10
181/181 [==============================] - 0s 2ms/sample - loss: 0.2452 - accuracy: 0.8895
Epoch 2/10
181/181 [==============================] - 0s 2ms/sample - loss: 0.2319 - accuracy: 0.8840
Epoch 3/10
181/181 [==============================] - 0s 2ms/sample - loss: 0.2417 - accuracy: 0.8785
Epoch 4/10
181/181 [==============================] - 0s 2ms/sample - loss: 0.2245 - accuracy: 0.8895
Epoch 5/10
181/181 [==============================] - 0s 2ms/sample - loss: 0.2168 - accuracy: 0.9006
Epoch 6/10
181/181 [==============================] - 0s 2ms/sample - loss: 0.2081 - accuracy: 0.9006
Epoch 7/10
181/181 [==============================] - 0s 3ms/sample - loss: 0.1990 - accuracy: 0.9006
Epoch 8/10
181/181 [==============================] - 0s 2ms/sample - loss: 0.1961 - accuracy: 0.9171
Epoch 9/10
181/181 [==============================] - 0s 3ms/sample - loss: 0.1877 - accuracy: 0.9116
Epoch 10/10
181/181 [==============================] - 0s 2ms

In [49]:
model.predict(x_test)

array([[9.92692471e-01],
       [2.37810612e-03],
       [8.94069672e-08],
       [2.27144867e-01],
       [3.34382057e-05],
       [4.09880280e-03],
       [4.32133675e-06],
       [0.00000000e+00],
       [3.86774808e-01],
       [8.21923375e-01],
       [9.69170034e-02],
       [2.32458115e-06],
       [5.00977039e-04],
       [1.33991241e-04],
       [9.63836551e-01],
       [1.23560429e-04],
       [1.61731243e-03],
       [6.16336226e-01],
       [3.63945961e-04],
       [9.83159065e-01],
       [9.99500394e-01],
       [4.47263062e-01],
       [4.58478630e-02],
       [0.00000000e+00],
       [2.71052122e-04],
       [4.69416380e-03],
       [6.99323416e-03],
       [9.85670090e-01],
       [4.25890088e-03],
       [1.53015256e-01],
       [2.03847885e-05],
       [8.31347704e-02],
       [1.99675560e-06],
       [7.60269165e-03],
       [1.51991844e-06],
       [0.00000000e+00],
       [8.01681042e-01],
       [1.43411756e-03],
       [5.48031926e-03],
       [8.94069672e-08],


In [50]:
model.predict_classes(x_test)

array([[1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
    

In [51]:
model.evaluate(x_test,y_test)

122/122 [==============================] - 0s 761us/sample - loss: 0.5747 - accuracy: 0.8197


[0.574673056602478, 0.8196721]